version: '3.8'

services:
  php:
    image: bloodriver/php:v1.0
    volumes:
      - ./php/src:/var/www/html
    networks:
      - app-network

  composer:
    image: bloodriver/composer:v1.0
    tty: true
    volumes:
      - ./composer/src:/var/www/html
    networks:
      - app-network
    depends_on:
      - php

  symfony:
    image: bloodriver/symfony:v1.0
    tty: true
    volumes:
      - ./Project-Symfony:/var/www/html/Project-Symfony
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - php
    command: php -S 0.0.0.0:8000 -t public
    # command: composer create-project symfony/skeleton:"7.0.*" ./

  adminer:
    image: bloodriver/adminer:v1.0
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    external: true
