version: '3.7'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./symfony/public:/public
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    image: your-custom-php-fpm-image
    build:
      context: ./path-to-your-custom-php-fpm-dockerfile
    volumes:
      - ./symfony:/symfony
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

  postgres:
    image: your-custom-postgres-image
    build:
      context: ./path-to-your-custom-postgres-dockerfile
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: your-custom-adminer-image
    build:
      context: ./path-to-your-custom-adminer-dockerfile
    ports:
      - "8080:8080"

volumes:
  pgdata:
