version: '3.7'

services:
  adminer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./adminer.conf:/etc/apache2/conf.d/adminer.conf
      - ./htpasswd:/etc/apache2/.htpasswd
      - ./adminer.php:/var/www/localhost/htdocs/adminer/index.php
    depends_on:
      - postgres  

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
